/**
 * All user-facing Italian strings live here. Components never hard-code copy.
 * Keep the tone plain and calm: no exclamation marks, no praise, no guilt.
 */
export const t = {
  appName: 'Zenfullness',
  tabs: {
    label: 'Sezioni',
    today: 'Oggi',
    zazen: 'Zazen',
    breath: 'Respiro',
    guided: 'Guidate',
    history: 'Storico',
  },
  greeting: {
    morning: 'Buongiorno',
    afternoon: 'Buon pomeriggio',
    evening: 'Buonasera',
  },
  today: {
    otherPractices: 'Altre pratiche',
  },
  settings: {
    title: 'Impostazioni',
    open: 'Apri le impostazioni',
    back: 'Torna indietro',
    version: 'Versione',
    offline: 'Uso senza rete',
    offlineReady: 'Pronta',
    offlinePending: 'In preparazione',
    offlineUnsupported: 'Non disponibile in questo browser',
    bellVolume: 'Volume campane',
    testBell: 'Prova',
    testBellLabel: 'Prova il volume delle campane',
  },
  update: {
    available: 'È disponibile una nuova versione.',
    apply: 'Aggiorna',
  },
  zazen: {
    title: 'Zazen',
    minutes: 'minuti',
    decrease: 'Un minuto in meno',
    increase: 'Un minuto in più',
    presets: 'Durate',
    sequence: 'Sequenza',
    periodName: { zazen: 'Zazen', kinhin: 'Kinhin' },
    editing: 'in modifica',
    addRound: 'Aggiungi kinhin e zazen',
    removeRound: "Togli l'ultimo giro",
    prep: 'Preparazione',
    prepNone: 'Nessuna',
    bells: 'Campane',
    bellSets: { traditional: 'Tradizionali', inkin: 'Inkin', wood: 'Legno' },
    midBell: 'Campana a metà',
    showTime: 'Mostra tempo',
    yes: 'Sì',
    no: 'No',
    savePreset: 'Salva come durata',
    deletePreset: 'Elimina questa durata',
    start: 'Inizia la seduta',
  },
  sitting: {
    prep: 'Preparazione',
    of: 'di',
    paused: 'In pausa',
    pause: 'Pausa',
    resume: 'Riprendi',
    end: 'Termina',
    confirmEnd: 'Tocca ancora per terminare',
    remaining: 'Tempo rimanente nel periodo',
    doneTitle: 'Seduta conclusa',
    doneEarly: 'Seduta interrotta',
    duration: 'Durata',
    close: 'Chiudi',
    audioBlocked: "L'audio è sospeso. Tocca lo schermo per riattivarlo.",
  },
  placeholder: {
    comingSoon: 'Questa sezione arriverà presto.',
  },
} as const;
