/**
 * All user-facing Italian strings live here. Components never hard-code copy.
 * Keep the tone plain and calm: no exclamation marks, no praise, no guilt.
 */
export const t = {
  appName: 'Zenfullness',
  tabs: {
    label: 'Sezioni',
    today: 'Oggi',
    zazen: 'Zazen',
    breath: 'Respiro',
    guided: 'Guidate',
    history: 'Storico',
  },
  greeting: {
    morning: 'Buongiorno',
    afternoon: 'Buon pomeriggio',
    evening: 'Buonasera',
  },
  today: {
    otherPractices: 'Altre pratiche',
    breathing: 'Respirazione',
    guided: 'Guidata',
    guidedSoon: 'Meditazioni guidate',
    soundscape: 'Paesaggio sonoro',
  },
  soundscape: {
    title: 'Paesaggio sonoro',
    back: 'Torna a Oggi',
    layers: 'Suoni',
    names: { rain: 'Pioggia', wind: 'Vento', water: 'Acqua', drone: 'Bordone' },
    level: 'Volume',
    silence: 'Silenzio',
    volume: 'Volume ambiente',
    listen: 'Ascolta',
    stop: 'Ferma',
    note: 'Suoni generati in tempo reale: non si ripetono mai uguali.',
  },
  settings: {
    title: 'Impostazioni',
    open: 'Apri le impostazioni',
    back: 'Torna indietro',
    version: 'Versione',
    offline: 'Uso senza rete',
    offlineReady: 'Pronta',
    offlinePending: 'In preparazione',
    offlineUnsupported: 'Non disponibile in questo browser',
    bellVolume: 'Volume campane',
    ambientVolume: 'Volume ambiente',
    testBell: 'Prova',
    testBellLabel: 'Prova il volume delle campane',
  },
  update: {
    available: 'È disponibile una nuova versione.',
    apply: 'Aggiorna',
  },
  zazen: {
    title: 'Zazen',
    minutes: 'minuti',
    decrease: 'Un minuto in meno',
    increase: 'Un minuto in più',
    presets: 'Durate',
    sequence: 'Sequenza',
    periodName: { zazen: 'Zazen', kinhin: 'Kinhin' },
    editing: 'in modifica',
    addRound: 'Aggiungi kinhin e zazen',
    removeRound: "Togli l'ultimo giro",
    prep: 'Preparazione',
    prepNone: 'Nessuna',
    bells: 'Campane',
    bellSets: { traditional: 'Tradizionali', inkin: 'Inkin', wood: 'Legno' },
    midBell: 'Campana a metà',
    showTime: 'Mostra tempo',
    ambient: 'Ambiente',
    yes: 'Sì',
    no: 'No',
    savePreset: 'Salva come durata',
    deletePreset: 'Elimina questa durata',
    start: 'Inizia la seduta',
  },
  sitting: {
    prep: 'Preparazione',
    of: 'di',
    paused: 'In pausa',
    pause: 'Pausa',
    resume: 'Riprendi',
    end: 'Termina',
    confirmEnd: 'Tocca ancora per terminare',
    remaining: 'Tempo rimanente nel periodo',
    doneTitle: 'Seduta conclusa',
    doneEarly: 'Seduta interrotta',
    duration: 'Durata',
    close: 'Chiudi',
    audioBlocked: "L'audio è sospeso. Tocca lo schermo per riattivarlo.",
  },
  breath: {
    title: 'Respiro',
    patterns: 'Schemi',
    chip: {
      susokukan: 'Susokukan',
      square: 'Quadrato',
      long46: '4–6',
      long478: '4–7–8',
      coherence: 'Coerenza',
      custom: 'Personale',
    },
    name: {
      susokukan: 'Conteggio dei respiri',
      square: 'Respiro quadrato',
      long46: 'Espirazione lunga',
      long478: 'Espirazione lunga',
      coherence: 'Coerenza',
      custom: 'Personale',
    },
    perMinute: 'al minuto',
    countRange: '1–10',
    phase: { inhale: 'inspira', holdIn: 'trattieni', exhale: 'espira', holdOut: 'pausa' },
    phaseLong: {
      inhale: 'Inspirazione',
      holdIn: 'Pausa a polmoni pieni',
      exhale: 'Espirazione',
      holdOut: 'Pausa a polmoni vuoti',
    },
    counts: ['uno', 'due', 'tre', 'quattro', 'cinque', 'sei', 'sette', 'otto', 'nove', 'dieci'],
    ready: 'pronto',
    duration: 'Durata',
    sound: 'Suono',
    haptics: 'Vibrazione',
    ambient: 'Ambiente',
    edit: 'Modifica',
    editTitle: 'Schema personale',
    seconds: 's',
    less: 'meno',
    more: 'più',
    done: 'Fatto',
    start: 'Inizia',
    pause: 'Pausa',
    resume: 'Riprendi',
    end: 'Termina',
    finished: 'Respiro concluso',
    endedEarly: 'Respiro interrotto',
  },
  placeholder: {
    comingSoon: 'Questa sezione arriverà presto.',
  },
} as const;
